apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: sdavdf/books:latest
          env:
            - name: APP_AUTHORS_URL
              value: http://authors-service:9090
            - name: DB_HOST
              value: db.example.com
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: books_user
            - name: DB_PASSWORD
              value: books_password
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  type: ClusterIP
  selector:
    app: books
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authors
  template:
    metadata:
      labels:
        app: authors
    spec:
      containers:
        - name: authors
          image: sdavdf/authors:latest
          ports:
            - containerPort: 9090
          env:
            - name: DB_HOST
              value: db.example.com
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: authors_user
            - name: DB_PASSWORD
              value: authors_password
---
apiVersion: v1
kind: Service
metadata:
  name: authors-service
spec:
  type: ClusterIP
  selector:
    app: authors
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: sdavdf/web:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: db.example.com
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: web_user
            - name: DB_PASSWORD
              value: web_password
          livenessProbe:
            httpGet:
              port: 8081
              path: /q/health/live
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
